service: media-api-ecommerce

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  memorySize: 128
  versionFunctions: false
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    PORT: ${env:PORT}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-nested-stack

custom:
  serverless-offline:
    port: ${env:PORT}
    host: "0.0.0.0"

  webpack:
    webpackConfig: internals/webpack.js

# ========================= #
#  ALL REST ENDPOINTS HERE  #
# ========================= #
functions:
  # SETTING IMAGE
  SETTING__IMAGE___create:
    handler: src/handler.SETTING__IMAGE___create
    events:
      - http:
          path: /settings/image
          method: post
  # SETTING IMAGE --- END
